Migrate docker images to ghcr registry
terascope/base-docker-image pull request #33
Opened 2024-07-15 18:43 UTC by sotojn

TBD

2024-07-15 21:33 UTC, godber commented
Rename this PR to match what it does

I had meant for you to build a single image and tag it with multiple tags, somewhat like this:

```
docker build 22.2.0
docker tag 22.2.0 22.2
docker tag 22.2.0 22
docker push 22.2.0
docker push 22.2
docker push 22
```

Instead you are doing this, we won't end up with the right versions in these tags ... 

```
docker build 22.2.0 
docker push 22.2.0  <- 22.2.0
docker build 22.2
docker push 22.2     <- 22.2.?
docker build 22        <- 22.4.1
docker push 22  
```

We always want to have the latest major node version at build time.  See if you can rework this.

2024-07-16 22:44 UTC, godber commented
This PR is meant to address the first part of this issue: https://github.com/terascope/teraslice/issues/3683

2024-07-17 20:36 UTC, busma13 approved these changes
Looks good.

2024-07-18 00:13 UTC, godber commented on .github/workflows/build.yml
> +        # Ex: ["18", "20", "22"] ---> ["18.19.1", "20", "22"]
Unfortunately I've just realized how this isn't going to achieve what we want.  By going from `18` to `18.19.1`, the `build-push-action` will go from pushing `18` to pushing `18.19.1` and won't update the `18` tag.  I mistakenly thought the code on 51-68 managed the major number as well.

2024-07-18 20:15 UTC, godber requested changes

2024-07-18 20:15 UTC, godber commented on .github/workflows/build.yml
> +        version: ["18.19.1", "20", "22"]
```suggestion
        version: ["18", "20", "22"]
```

Get rid of minor.patch.

2024-07-18 21:00 UTC, godber approved these changes

2024-07-18 21:01 UTC, godber commented
I'm going to go on record here and point out that we were burned by the major number `22` before we even managed to merge this PR.  Yesterday everything was fine, today, 22.5.0 came out and broke the kafka install, so we've pinned `22` -> `22.4.1`.  We will need to remember to address the issue and then come back and unpin it.

2024-07-18 21:02 UTC, merged