Migrate docker images from docker.hub to ghcr registry
terascope/base-docker-image pull request #34
Opened 2024-07-22 22:23 UTC by sotojn

- TBD

2024-07-24 16:56 UTC, busma13 requested changes

2024-07-24 16:56 UTC, busma13 commented on Dockerfile
> +  org.opencontainers.image.kafka_connector_version="1.0.0"
I don't think these should start with `org.opencontainers.image`.

2024-07-24 16:56 UTC, busma13 commented on Dockerfile.core
> +  org.opencontainers.image.node_version="$NODE_VERSION"
Same here

2024-07-24 17:46 UTC, busma13 approved these changes
Looks good

2024-07-24 23:38 UTC, godber approved these changes
I'll accept and merge my recommended changes.

2024-07-24 23:38 UTC, godber commented on Dockerfile
> +  kafka_connector_version="1.0.0"
```suggestion
  io.terascope.image.node_version="$NODE_VERSION" \
  io.terascope.image.kafka_connector_version="1.0.0"
```

We should namespace any custom labels we add, here's the spec: https://github.com/opencontainers/image-spec/blob/main/annotations.md

2024-07-24 23:38 UTC, godber commented on Dockerfile.core
> +  node_version="$NODE_VERSION"
```suggestion
  io.terascope.image.node_version="$NODE_VERSION" 
```

2024-07-25 15:37 UTC, godber approved these changes

2024-07-25 15:37 UTC, merged